//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraDownload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public program()
        {
            this.comment = new HashSet<comment>();
            this.downloaded = new HashSet<downloaded>();
            this.favourite = new HashSet<favourite>();
        }
    
        public int program_id { get; set; }
        public string program_name { get; set; }
        public int category_id { get; set; }
        public int user_id { get; set; }
        public int download_count { get; set; }
        public string link64 { get; set; }
        public string link32 { get; set; }
        public string iconS { get; set; }
        public string iconM { get; set; }
        public string iconL { get; set; }
        public string explanation { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<downloaded> downloaded { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite> favourite { get; set; }
        public virtual user user { get; set; }
    }
}
